spring.application.name=fitnessApplication

spring.datasource.url = jdbc:mysql://localhost:3306/fitness_application_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# --- Edamam API Configuration ---
edamam.api.url=https://api.edamam.com/api/food-database/v2/parser
edamam.api.appId=43a87ece
edamam.api.appKey=de316c3dc712c96fa9196804dd312f9c